### ISSUE TITLE
Bootstrap should ignore windows scale setting

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#16] opened 2017-06-29 11:02 UTC
UI at scale 125%
![image](https://user-images.githubusercontent.com/9715314/27684623-0ae0b8a0-5ccb-11e7-8ba3-8a28b87af03c.png)

UI at scale 100%
![image](https://user-images.githubusercontent.com/9715314/27684640-1c2f9b3a-5ccb-11e7-9089-e0996837d4ed.png)

This is not the browser zoom, but a windows setting.
At ishadijcks.github.io we did not have this problem, so it is possible.

**Comment by Aegyo** [comment] 2017-06-29 14:16
Do you want help with this? It's hard to tell since you have assigned it already to yourself, but have the "help wanted" label.

**Comment by Ishadijcks** [comment] 2017-06-29 14:18
Ah I thought I had cleared the self-assignment.
Yeah I'd like some help on this :)

**Comment by dennism1997** [comment] 2017-06-29 14:18
The layout is a bit different with the background, but the size difference is still there

**Comment by Aegyo** [comment] 2017-06-29 14:36
I'm actually not entirely sure what the problem is, do you want the UI elements to take up more space on larger screens?

**Comment by dennism1997** [comment] 2017-06-29 14:38
The size of the elements should be the same on all screens with the same resolution. However, in windows there is a setting that apparently changes the size of the elements, as you can see on the pictures. I hope this makes it more clear

**Comment by Aegyo** [comment] 2017-06-29 15:45
Setting the container size to a percentage seems to produce the same behaviour that was on ishadijcks.github.io, font sizes are still increased though with that windows setting. Should I make a pr with this change?

**Comment by Ishadijcks** [comment] 2017-06-29 15:47
Yes please.
I thought bootstrap container class automatically had a width of 80%

**Closed** 2017-06-29 16:05 UTC
Labels: bug, help wanted
